//! TASKS.md `--commit` frontmatter rewriter.
//!
//! Narrow helper backing `speccy tasks SPEC-NNNN --commit` (SPEC-0006).
//! Rewrites the two managed frontmatter fields
//! (`spec_hash_at_generation`, `generated_at`) while preserving every
//! body byte after the closing `---` fence byte-identically.
//!
//! The rewrite is line-level: each top-level YAML key is either replaced
//! in-place (preserving line ending and field order, per SPEC-0006 DEC-002
//! and REQ-004 behaviour) or appended in canonical order if missing.
//! Other frontmatter fields (e.g. agent-added notes) are copied verbatim.
//!
//! See `.speccy/specs/0006-tasks-command/SPEC.md`.

use crate::error::ParseError;
use crate::parse::frontmatter::Split;
use crate::parse::frontmatter::split as split_frontmatter;
use camino::Utf8Path;
use camino::Utf8PathBuf;
use jiff::Timestamp;
use std::fmt::Write as _;
use thiserror::Error;

/// Failure mode of [`commit_frontmatter`].
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum CommitError {
    /// TASKS.md does not exist for the named spec.
    #[error("TASKS.md not found at {path}; was it generated by the agent?")]
    TasksMdNotFound {
        /// Expected path to TASKS.md.
        path: Utf8PathBuf,
    },
    /// TASKS.md frontmatter declares a `spec` value that differs from the
    /// SPEC-ID argument supplied on the command line. The file is **not**
    /// modified.
    #[error(
        "TASKS.md spec field `{in_file}` does not match SPEC-ID argument `{in_arg}`; \
         refusing to overwrite (file untouched)"
    )]
    SpecIdMismatch {
        /// Value found in the existing TASKS.md frontmatter.
        in_file: String,
        /// Value supplied as the command argument.
        in_arg: String,
    },
    /// I/O error reading or writing TASKS.md.
    #[error("I/O error processing TASKS.md")]
    Io(#[source] std::io::Error),
    /// Frontmatter splitter failed (e.g. unterminated `---` fence).
    #[error("failed to parse TASKS.md frontmatter")]
    Parse(#[source] Box<ParseError>),
}

impl From<std::io::Error> for CommitError {
    fn from(err: std::io::Error) -> Self {
        CommitError::Io(err)
    }
}

impl From<ParseError> for CommitError {
    fn from(err: ParseError) -> Self {
        CommitError::Parse(Box::new(err))
    }
}

/// Rewrite TASKS.md frontmatter at `tasks_md_path`, recording the SPEC.md
/// content hash and the supplied UTC moment.
///
/// `spec_id` is the canonical `SPEC-NNNN` argument from the CLI.
/// `spec_md_sha256` is the raw SPEC.md content hash from
/// [`crate::parse::SpecMd::sha256`]. `now_utc` is the moment captured at
/// command start; truncated to second precision and rendered as
/// `YYYY-MM-DDTHH:MM:SSZ` (SPEC-0006 DEC-004).
///
/// The file's body bytes (everything after the closing `---` fence) are
/// preserved byte-identically. Frontmatter fields that are not managed
/// here are copied verbatim, preserving their declared order. Missing
/// managed fields are appended in canonical order (`spec`,
/// `spec_hash_at_generation`, `generated_at`).
///
/// # Errors
///
/// Returns [`CommitError::TasksMdNotFound`] if the file doesn't exist,
/// [`CommitError::SpecIdMismatch`] if the frontmatter `spec` value does
/// not match `spec_id` (the file is not modified in this case),
/// [`CommitError::Parse`] if the frontmatter fence is malformed, or
/// [`CommitError::Io`] on read/write failure.
pub fn commit_frontmatter(
    tasks_md_path: &Utf8Path,
    spec_id: &str,
    spec_md_sha256: &[u8; 32],
    now_utc: Timestamp,
) -> Result<(), CommitError> {
    let raw = match fs_err::read_to_string(tasks_md_path.as_std_path()) {
        Ok(s) => s,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            return Err(CommitError::TasksMdNotFound {
                path: tasks_md_path.to_path_buf(),
            });
        }
        Err(err) => return Err(CommitError::Io(err)),
    };

    let hash_hex = hex_of_sha256(spec_md_sha256);
    let ts_str = format_iso_z(now_utc);

    let split = split_frontmatter(&raw, tasks_md_path)?;
    let new_content = match split {
        Split::None => prepend_fresh_frontmatter(spec_id, &hash_hex, &ts_str, &raw),
        Split::Some { yaml, body } => {
            if let Some(existing) = find_top_level_spec(yaml)
                && existing != spec_id
            {
                return Err(CommitError::SpecIdMismatch {
                    in_file: existing,
                    in_arg: spec_id.to_owned(),
                });
            }
            let eol = detect_line_ending(yaml);
            let new_yaml = rewrite_yaml(yaml, spec_id, &hash_hex, &ts_str, eol);
            format!("---{eol}{new_yaml}---{eol}{body}")
        }
    };

    fs_err::write(tasks_md_path.as_std_path(), new_content)?;
    Ok(())
}

fn hex_of_sha256(bytes: &[u8; 32]) -> String {
    let mut s = String::with_capacity(64);
    for b in bytes {
        if write!(s, "{b:02x}").is_err() {
            break;
        }
    }
    s
}

fn format_iso_z(ts: Timestamp) -> String {
    let secs = ts.as_second();
    Timestamp::from_second(secs).map_or_else(|_| ts.to_string(), |t| t.to_string())
}

fn detect_line_ending(yaml: &str) -> &'static str {
    if yaml.contains("\r\n") { "\r\n" } else { "\n" }
}

fn prepend_fresh_frontmatter(spec_id: &str, hash_hex: &str, ts_str: &str, body: &str) -> String {
    let eol = detect_line_ending(body);
    format!(
        "---{eol}spec: {spec_id}{eol}spec_hash_at_generation: {hash_hex}{eol}generated_at: {ts_str}{eol}---{eol}{body}",
    )
}

fn rewrite_yaml(yaml: &str, spec_id: &str, hash_hex: &str, ts_str: &str, eol: &str) -> String {
    let mut out = String::with_capacity(yaml.len().saturating_add(256));
    let mut saw_spec = false;
    let mut saw_hash = false;
    let mut saw_time = false;

    for line in yaml.split_inclusive('\n') {
        let (content, term) = split_line_term(line);
        if is_top_level_key(content, "spec_hash_at_generation") {
            out.push_str("spec_hash_at_generation: ");
            out.push_str(hash_hex);
            out.push_str(term);
            saw_hash = true;
        } else if is_top_level_key(content, "generated_at") {
            out.push_str("generated_at: ");
            out.push_str(ts_str);
            out.push_str(term);
            saw_time = true;
        } else {
            if is_top_level_key(content, "spec") {
                saw_spec = true;
            }
            out.push_str(line);
        }
    }

    if !saw_spec {
        out.push_str("spec: ");
        out.push_str(spec_id);
        out.push_str(eol);
    }
    if !saw_hash {
        out.push_str("spec_hash_at_generation: ");
        out.push_str(hash_hex);
        out.push_str(eol);
    }
    if !saw_time {
        out.push_str("generated_at: ");
        out.push_str(ts_str);
        out.push_str(eol);
    }

    out
}

fn split_line_term(line: &str) -> (&str, &'static str) {
    if let Some(content) = line.strip_suffix("\r\n") {
        (content, "\r\n")
    } else if let Some(content) = line.strip_suffix('\n') {
        (content, "\n")
    } else {
        (line, "")
    }
}

fn is_top_level_key(content: &str, key: &str) -> bool {
    if content.starts_with(' ') || content.starts_with('\t') {
        return false;
    }
    let Some(after) = content.strip_prefix(key) else {
        return false;
    };
    after.starts_with(':')
}

fn find_top_level_spec(yaml: &str) -> Option<String> {
    for line in yaml.lines() {
        if line.starts_with(' ') || line.starts_with('\t') {
            continue;
        }
        let Some(after) = line.strip_prefix("spec") else {
            continue;
        };
        let Some(rest) = after.strip_prefix(':') else {
            continue;
        };
        let trimmed = rest.trim();
        return Some(strip_quotes(trimmed).to_owned());
    }
    None
}

fn strip_quotes(value: &str) -> &str {
    if let Some(inner) = value.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
        return inner;
    }
    if let Some(inner) = value.strip_prefix('\'').and_then(|s| s.strip_suffix('\'')) {
        return inner;
    }
    value
}

#[cfg(test)]
mod tests {
    use super::detect_line_ending;
    use super::find_top_level_spec;
    use super::format_iso_z;
    use super::hex_of_sha256;
    use super::is_top_level_key;
    use super::split_line_term;
    use jiff::Timestamp;

    #[test]
    fn hex_of_sha256_is_64_chars_lowercase() {
        let bytes = [0xab_u8; 32];
        let hex = hex_of_sha256(&bytes);
        assert_eq!(hex.len(), 64);
        assert!(
            hex.chars()
                .all(|c| c.is_ascii_hexdigit() && !c.is_uppercase()),
            "hash must be lowercase ASCII hex: {hex}",
        );
        assert_eq!(hex, "ab".repeat(32));
    }

    #[test]
    fn format_iso_z_truncates_subsec_and_uses_z_suffix() {
        let ts = "2026-05-13T15:30:42.123456789Z"
            .parse::<Timestamp>()
            .expect("hardcoded ISO timestamp parses");
        let formatted = format_iso_z(ts);
        assert_eq!(formatted, "2026-05-13T15:30:42Z");
    }

    #[test]
    fn detect_line_ending_picks_crlf_when_present() {
        assert_eq!(detect_line_ending("key: value\r\nother: v\r\n"), "\r\n");
        assert_eq!(detect_line_ending("key: value\nother: v\n"), "\n");
        assert_eq!(detect_line_ending(""), "\n");
    }

    #[test]
    fn split_line_term_returns_correct_terminator() {
        assert_eq!(split_line_term("key: value\n"), ("key: value", "\n"));
        assert_eq!(split_line_term("key: value\r\n"), ("key: value", "\r\n"));
        assert_eq!(split_line_term("key: value"), ("key: value", ""));
    }

    #[test]
    fn is_top_level_key_rejects_indented_and_partial_matches() {
        assert!(is_top_level_key("spec: SPEC-0001", "spec"));
        assert!(is_top_level_key("spec:SPEC-0001", "spec"));
        assert!(!is_top_level_key("  spec: SPEC-0001", "spec"));
        assert!(!is_top_level_key("\tspec: SPEC-0001", "spec"));
        assert!(!is_top_level_key("spec_hash_at_generation: x", "spec"));
        assert!(is_top_level_key(
            "spec_hash_at_generation: x",
            "spec_hash_at_generation",
        ));
    }

    #[test]
    fn find_top_level_spec_extracts_unquoted_value() {
        let yaml = "spec: SPEC-0006\nspec_hash_at_generation: abc\n";
        assert_eq!(
            find_top_level_spec(yaml).as_deref(),
            Some("SPEC-0006"),
            "spec value must be returned verbatim without surrounding whitespace",
        );
    }

    #[test]
    fn find_top_level_spec_strips_double_and_single_quotes() {
        assert_eq!(
            find_top_level_spec("spec: \"SPEC-0006\"\n").as_deref(),
            Some("SPEC-0006"),
        );
        assert_eq!(
            find_top_level_spec("spec: 'SPEC-0006'\n").as_deref(),
            Some("SPEC-0006"),
        );
    }

    #[test]
    fn find_top_level_spec_skips_indented_lines() {
        let yaml = "other:\n  spec: nested-not-matched\nspec: SPEC-0006\n";
        assert_eq!(
            find_top_level_spec(yaml).as_deref(),
            Some("SPEC-0006"),
            "indented `spec` keys must be ignored",
        );
    }

    #[test]
    fn find_top_level_spec_returns_none_when_absent() {
        let yaml = "spec_hash_at_generation: x\ngenerated_at: y\n";
        assert!(find_top_level_spec(yaml).is_none());
    }
}
